<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| ---------------------------------------------------------------------------
| Suspect — Application-specific configuration
| ---------------------------------------------------------------------------
|
| pid_key
| --------
| The AES-256-CBC encryption key used to encrypt/decrypt person IDs in URLs.
| This MUST match the `hash_key` value in the dramslive project's
| `application/config/auth.php` so that links generated by dramslive can be
| consumed by suspect and vice-versa.
|
| Set this via an environment variable in your web-server vhost config:
|   SetEnv SUSPECT_PID_KEY "your-secret-key-here"
|
| Leave empty to use development fallback (plain base64 encoding).
| NEVER commit the real key to version control.
|
*/
$config['pid_key'] = getenv('SUSPECT_PID_KEY') ?: '';

/*
| ---------------------------------------------------------------------------
| SSO / Token configuration
| ---------------------------------------------------------------------------
|
| token_ttl
| ---------
| How long (in seconds) an access token remains valid once issued.
| Default: 3600 (1 hour).  Production tokens from ctd.drams.com carry their
| own `expires` timestamp in the `user_tokens` table — this value is only
| used when generating new tokens internally.
|
*/
$config['token_ttl'] = 3600;

/*
| ---------------------------------------------------------------------------
| Person listing defaults
| ---------------------------------------------------------------------------
*/
$config['persons_per_page'] = 25;
